### ISSUE TITLE
mindone/examples/diffusers/text_to_image /train_text_to_image.py 冻结可训练参数函数BUG

### ISSUE THREAD

**Issue by ultranationalism** [mindspore-lab/mindone#486]
# Freeze vae and text_encoder and set unet to trainable
    def freeze_params(m: nn.Cell):
        for p in m.get_parameters():
            p.require_grad = False
应为
    # Freeze vae and text_encoder and set unet to trainable
    def freeze_params(m: nn.Cell):
        for p in m.get_parameters():
            p.requires_grad = False

**Comment by geniuspatrick** [comment]
fixed in #487
