### ISSUE TITLE
Lora微调参数问题咨询

### ISSUE THREAD

**Issue by jxzhang789** [mindspore-lab/mindone#578]
想了解下对于Lora微调是否有如下参数可以进行配置呢？
1.对于Lora网络，是否有参数lora_alpha进行设置

2.学习率调整策略，是否有cosine_with_restarts进行替换

**Comment by vigo999** [comment]
请问是哪个模型？

**Comment by SamitHuang** [comment]
Hi @jxzhang789 , 谢谢你对mindone的关注。
1. lora_alpha参数用于控制lora部分的scale，对于mindone/examples下的Stable Diffusion则是通过`lora_scale`来配置，与lora_alpha的关系为 `lora_scale=lora_rank / lora_alpha`，取值范围[0,1]。如果基于`mindone/diffusers/_peft`构建Lora微调流程，可配置未归一化的lora_alpha参数。
2. `mindone/trainers/lr_schedule.py`的`create_scheduler`接口提供了cosine_with_restarts相应的实现。比如lora微调10轮，共1000步，让学习率按cosine头500步内1e-3衰减到1e-4，再restart一次重新衰减，则可以这么调用
```
learning_rates = create_scheduler(
   steps_per_epoch=100,
   num_epochs=10,
   decay_steps=500,
   num_cycles=2,
   name="cosine_decay",
   lr=1e-3,
   end_lr=1e-4,
)
```

**Comment by jxzhang789** [comment]
> Hi @jxzhang789 , 谢谢你对mindone的关注。
> 
> 1. lora_alpha参数用于控制lora部分的scale，对于mindone/examples下的Stable Diffusion则是通过`lora_scale`来配置，与lora_alpha的关系为 `lora_scale=lora_rank / lora_alpha`，取值范围[0,1]。如果基于`mindone/diffusers/_peft`构建Lora微调流程，可配置未归一化的lora_alpha参数。
> 2. `mindone/trainers/lr_schedule.py`的`create_scheduler`接口提供了cosine_with_restarts相应的实现。比如lora微调10轮，共1000步，让学习率按cosine在头500步内1e-3衰减到1e-4，再restart一次重新衰减，则可以这么调用
> 
> ```python
> from mindone.trainers.lr_schedule import create_scheduler
> 
> learning_rates = create_scheduler(
>    steps_per_epoch=100,
>    num_epochs=10,
>    decay_steps=500,
>    num_cycles=2,
>    name="cosine_decay",
>    lr=1e-3,
>    end_lr=1e-4,
> )
> ```

好的，多谢这么详细的回复
