### ISSUE TITLE
RuntimeError: The pointerThost tensor is null. (when training t2i-adapter)

### ISSUE THREAD

**Issue by flyywh** [mindspore-lab/mindone#692]
Thanks for sending an issue!  Here are some tips for you:

If this is your first time, please read our contributor guidelines: https://github.com/mindspore-ai/mindspore/blob/master/CONTRIBUTING.md

## Hardware Environment | 硬件环境
 -  please tell us what kind of hardware can reproduce your error?
  请告诉我们您报错的后端类型
    - [X] `Ascend`
    - [ ] `GPU`
    - [ ] `CPU`

### Software Environment | 软件环境
- MindSpore version:
请告诉我们您正在使用的MindSpore版本：
  - [ ] 2.1
  - [ ] 2.0.0
  - [x] other (please state here): ___2.3.1___
- Python version(e.g., 3.7.5): 3.9.18
- OS(e.g., Linux Ubuntu 16.04): EulerOS release 2.0 (SP8)
- GCC/Compiler version: cc version 7.3.0 (GCC)

## Describe the current behavior | 目前输出
RuntimeError: The pointerThost tensor is null.
This exception is caused by framework's unexpected error. 

## Describe the expected behavior | 期望输出
please describe expected outputs or functions you want to have:
请告诉我们您期望得到的结果或功能
正常运行，开始训练

## Steps to reproduce the issue | 复现报错的步骤
1. cd examples/t2i_adapter/
2. python train_t2i_adapter_sd.py \
--config configs/sd_v2.1_train.yaml \
--train.dataset.init_args.image_dir ./data_all/train2017_RGB \
--train.dataset.init_args.masks_path ./data_all/train2017_RGB_Mask  \
--train.dataset.init_args.label_path ./data_all/annotations/captions_train2017.json \
--train.output_dir ./outputs

## Related log / screenshot | 完整日志
![temp](https://github.com/user-attachments/assets/0cf011f8-13d5-4e06-8dff-5d12e2e5b45b)

**Comment by flyywh** [comment]
Add MindSpore Version Info.

**Comment by vigo999** [comment]
ascend driver/firmware/cann toolkit version有吗

**Comment by flyywh** [comment]
已经解决了，设置unset RANK_TABLE_FILE后可以
